 export const MenuItems = [
    {
        title:"Dashboard",
        url:"/dashboard",
        class_name:"nav-items"
    },
    {
        title:"Matches",
        url:"/matches",
        class_name:"nav-items"
    },
    {
        title:"Teams",
        url:"/teams",
        class_name:"nav-items"
    },
    {
        title:"Tournament",
        url:"/tournament",
        class_name:"nav-items"
    },
    {
        title:"Account",
        url:"#",
        class_name:"nav-items"
    },
    {
        title:"Log out",
        url:"#",
        class_name:"nav-items"
    }
];